function [budengshi]=aaabudengshi_constraint(X,slip) 
mu=slip.mu;
U_MAX=10;
V_MAX=10;
A_MAX=10;
x=X(1);
dx=X(2);
ddx=X(3);
y=X(4);
dy=X(5);
ddy=X(6);

lq1=X(7);
lqd1=X(8);
lqdd1=X(9);
lq2=X(10);
lqd2=X(11);
lqdd2=X(12);
lq3=X(13);
lqd3=X(14);
lqdd3=X(15);

rq1=X(16);
rqd1=X(17);
rqdd1=X(18);
rq2=X(19);
rqd2=X(20);
rqdd2=X(21);
rq3=X(22);
rqd3=X(23);
rqdd3=X(24);

ltal1=X(25);
ltal2=X(26);
ltal3=X(27);

rtal1=X(28);
rtal2=X(29);
rtal3=X(30);

Flx=X(31);
Fly=X(32);
Frx=X(33);
Fry=X(34);
%% acc constraint
joint_acc_range_constraint=[...
    -lqdd1-A_MAX;...
    lqdd1-A_MAX;...
    -lqdd2-A_MAX;...
    lqdd2-A_MAX;...
    -lqdd3-A_MAX;...
    lqdd3-A_MAX;...
    -rqdd1-A_MAX;...
    rqdd1-A_MAX;...
    -rqdd2-A_MAX;...
    rqdd2-A_MAX;...
    -rqdd3-A_MAX;...
    rqdd3-A_MAX];

%% vel constraint
joint_vel_range_constraint=[...
    -lqd1-V_MAX;...
    lqd1-V_MAX;...
    -lqd2-V_MAX;...
    lqd2-V_MAX;...
    -lqd3-V_MAX;...
    lqd3-V_MAX;...
    -rqd1-V_MAX;...
    rqd1-V_MAX;...
    -rqd2-V_MAX;...
    rqd2-V_MAX;...
    -rqd3-V_MAX;...
    rqd3-V_MAX];
%% joint input constraint
joint_u_range_constraint=[...
    -ltal1-U_MAX;...
    ltal1-U_MAX;...
    -ltal2-U_MAX;...
    ltal2-U_MAX;...
    -ltal3-U_MAX;...
    ltal3-U_MAX;...
    -rtal1-U_MAX;...
    rtal1-U_MAX;...
    -rtal2-U_MAX;...
    rtal2-U_MAX;...
    -rtal3-U_MAX;...
    rtal3-U_MAX];

%% contact force friction constraint
z_l_arm=[lq1;lq2;lq3;lqd1;lqd2;lqd3];
z_2_arm=[rq1;rq2;rq3;rqd1;rqd2;rqd3];

[~, ~,lP3,~,~,~]=kinematic1(z_l_arm,slip);
[~, ~,rP3,~,~,~]=kinematic2(z_2_arm,slip);
Pc=[x;y];

distance1=Pc-lP3;
direction1=distance1/norm(distance1);
tan_direction1=[direction1(2);-direction1(1)];

distance2=Pc-rP3;
direction2=distance2/norm(distance2);
tan_direction2=[direction2(2);-direction2(1)];

F1=[Flx;Fly];
F2=[Frx;Fry];
Fnt1=[dot(F1,direction1);
dot(F1,tan_direction1)];

Fnt2=[dot(F2,direction2);
dot(F2,tan_direction2)];
        B=[-mu, 1;
            -mu, -1;
            -1,0];
        Aineq1=B*Fnt1;
        Aineq2=B*Fnt2;

friction_constraint=[...
    Aineq1;...
    Aineq2];


budengshi=[friction_constraint];
