function [d,dir,CQ,v_tan_vec, v_rel,t] = pointToLineSegmentDistance(A, B, C, vA, vB, vC)
%generated by deepseek    
% 输入：
    %   A, B: 线段端点坐标 [x, y]
    %   C: 外部点坐标 [x, y]
    %   vA, vB: A 和 B 的速度 [vx, vy]
    %   vC: C 点的速度 [vx, vy]
    % 输出：
    %   v_tan: 切向相对速度（标量）
    %   v_norm: 法向相对速度（标量）
    %   v_rel: 完整相对速度向量 [vx, vy]

    % 1. 计算最近点 Q 和投影参数 t
    AB = B - A;
    AC = C - A;
    AB_squared = sum(AB.^2);
    
    t = max(0, min(1, dot(AC, AB) / AB_squared));  % 限制 t 在 [0, 1] 范围内
    
    if t<1e-2
        t=1e-2;
    end

    Q = A + t * AB;
    
    CQ=C-Q;
    dir=CQ/norm(CQ);
    
    d = norm(CQ);

    % 2. 计算 Q 点的速度（线性插值）
    vQ = vA + t * (vB - vA);

    % 3. 计算 C 相对于 Q 的相对速度
    v_rel = vC - vQ;

    u_CQ = CQ / norm(CQ);  % 单位方向向量
    AQ=A-Q;
    u_AQ = AQ / norm(AQ);  % 单位方向向量

    v_norm = dot(v_rel, u_CQ);          % 切向分量（标量）
    v_tan_vec = dot(v_rel, u_AQ);  % 法向分量（向量）
